version: '3.8'

services:
  db:
    image: bitnami/postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgres

  cache:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=mysecret
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis

volumes:
  postgres_data:
  redis_data: